name: 'Deploy Frontend Production'
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  APP_NAME: 'cnc-recruit-frontend'
  REGISTRY_URL: 'registry.cnclab.cc'
  NAMESPACE: 'cnc-prod'
jobs:
  build:
    runs-on: 'self-hosted'
    permissions:
      id-token: write
      contents: read
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: 'registry.cnclab.cc'
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: 'Build and push container'
        run: |-
          IMAGE_NAME="${{ env.REGISTRY_URL }}/cnc/${{ env.APP_NAME }}"
          IMAGE_TAG="${GITHUB_REF#refs/*/}"

          docker build -f Dockerfile -t "${IMAGE_NAME}:${IMAGE_TAG}" .
          docker push "${IMAGE_NAME}:${IMAGE_TAG}"
  deploy:
    runs-on: 'self-hosted'
    permissions:
      id-token: write
      contents: read
    needs: 'build'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
        with:
          repository: cnc-csku/cnc-ops
          token: ${{ secrets.GH_PAT }}
          path: cnc-ops

      - name: Get the version from GITHUB_REF
        id: version
        run: |
          VERSION="${GITHUB_REF#refs/*/}"  # Extract version from the GitHub ref
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update version in vars.json in cnc-ops
        run: |
          echo "Updating version in cnc-ops vars.json in namespace ${{ env.NAMESPACE }} to $VERSION"
          jq --arg VERSION "$VERSION" --arg NAMESPACE "${{ env.NAMESPACE }}" '.["${{ env.NAMESPACE }}"].version = $VERSION' cnc-ops/projects/cnc/cnc-recruit-front/vars/vars.json > tmp.json && mv tmp.json cnc-ops/projects/cnc/cnc-recruit-front/vars/vars.json

      - name: Commit changes to cnc-ops
        run: |
          cd cnc-ops
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add projects/cnc/cnc-recruit-front/vars/vars.json
          git commit -m "Update version ${{ env.APP_NAME }} in namespace ${{ env.NAMESPACE }} to $VERSION"
          git push https://github.com/cnc-csku/cnc-ops.git HEAD:main
